[package]
name = "node"
version = "0.1.0"
authors = ["Knarkzel <knarkzel@cock.li>"]
edition = "2018"

[dependencies]
rustyline = "6.3.0"
owo-colors = "1.1.3"
anyhow = "1.0.33"
serde = "1.0.117"
ron = "0.6.2"
